export const Data = [
  {
    id: 1,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для создания ссылки?",
    options: ["<link>", "<a>", "<href>", "<url>"],
    correctAnswerIndex: 1,
    explanation: "Тег <a> используется для создания гиперссылок.",
  },
  {
    id: 2,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой атрибут указывает адрес ссылки?",
    options: ["src", "href", "link", "url"],
    correctAnswerIndex: 1,
    explanation: "Атрибут href содержит адрес ссылки.",
  },
  {
    id: 3,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег задает самый важный заголовок страницы?",
    options: ["<header>", "<title>", "<h1>", "<h6>"],
    correctAnswerIndex: 2,
    explanation: "Заголовок первого уровня обозначается тегом <h1>.",
  },
  {
    id: 4,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для вставки изображения?",
    options: ["<image>", "<picture>", "<img>", "<src>"],
    correctAnswerIndex: 2,
    explanation: "Изображения вставляются с помощью тега <img>.",
  },
  {
    id: 5,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой атрибут обязателен для изображения?",
    options: ["href", "src", "alt", "title"],
    correctAnswerIndex: 1,
    explanation: "Минимально необходимым является атрибут src.",
  },
  {
    id: 6,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег создает нумерованный список?",
    options: ["<ul>", "<li>", "<ol>", "<list>"],
    correctAnswerIndex: 2,
    explanation: "<ol> создает упорядоченный список.",
  },
  {
    id: 7,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для элемента списка?",
    options: ["<item>", "<list>", "<li>", "<ul>"],
    correctAnswerIndex: 2,
    explanation: "Каждый элемент списка оформляется тегом <li>.",
  },
  {
    id: 8,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег создает ненумерованный список?",
    options: ["<ol>", "<ul>", "<list>", "<li>"],
    correctAnswerIndex: 1,
    explanation: "<ul> используется для маркированного списка.",
  },
  {
    id: 9,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для абзаца?",
    options: ["<text>", "<paragraph>", "<span>", "<p>"],
    correctAnswerIndex: 3,
    explanation: "Абзацы создаются тегом <p>.",
  },
  {
    id: 10,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для переноса строки?",
    options: ["<hr>", "<br>", "<break>", "<lb>"],
    correctAnswerIndex: 1,
    explanation: "Тег <br> выполняет перенос строки.",
  },
  {
    id: 11,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег создает горизонтальную линию?",
    options: ["<line>", "<hr>", "<br>", "<border>"],
    correctAnswerIndex: 1,
    explanation: "Тег <hr> отображает горизонтальную линию.",
  },
  {
    id: 12,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для кнопки?",
    options: ["<input>", "<button>", "<click>", "<btn>"],
    correctAnswerIndex: 1,
    explanation: "Кнопки создаются тегом <button>.",
  },
  {
    id: 13,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для формы?",
    options: ["<input>", "<form>", "<fieldset>", "<label>"],
    correctAnswerIndex: 1,
    explanation: "Все элементы формы объединяются тегом <form>.",
  },
  {
    id: 14,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для текстового поля?",
    options: ["<textarea>", "<input>", "<field>", "<text>"],
    correctAnswerIndex: 1,
    explanation: "Однострочное поле создается тегом <input>.",
  },
  {
    id: 15,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой атрибут делает поле обязательным?",
    options: ["validate", "required", "need", "must"],
    correctAnswerIndex: 1,
    explanation: "required запрещает отправку формы без заполнения поля.",
  },
  {
    id: 16,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для многострочного ввода?",
    options: ["<input>", "<textarea>", "<text>", "<area>"],
    correctAnswerIndex: 1,
    explanation: "<textarea> предназначен для многострочного текста.",
  },
  {
    id: 17,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег отображает выпадающий список?",
    options: ["<list>", "<option>", "<select>", "<dropdown>"],
    correctAnswerIndex: 2,
    explanation: "Выпадающий список создается тегом <select>.",
  },
  {
    id: 18,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег описывает вариант в select?",
    options: ["<value>", "<item>", "<option>", "<choice>"],
    correctAnswerIndex: 2,
    explanation: "Каждый вариант задается тегом <option>.",
  },
  {
    id: 19,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для таблицы?",
    options: ["<table>", "<grid>", "<tr>", "<tbody>"],
    correctAnswerIndex: 0,
    explanation: "Таблицы создаются тегом <table>.",
  },
  {
    id: 20,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег создает строку таблицы?",
    options: ["<td>", "<table>", "<tr>", "<th>"],
    correctAnswerIndex: 2,
    explanation: "Строки таблицы задаются тегом <tr>.",
  },
  {
    id: 21,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег создает ячейку таблицы?",
    options: ["<cell>", "<td>", "<tr>", "<th>"],
    correctAnswerIndex: 1,
    explanation: "Обычная ячейка таблицы обозначается тегом <td>.",
  },
  {
    id: 22,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег обозначает заголовочную ячейку таблицы?",
    options: ["<thead>", "<header>", "<th>", "<caption>"],
    correctAnswerIndex: 2,
    explanation: "Заголовки столбцов оформляются тегом <th>.",
  },
  {
    id: 23,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег содержит метаданные страницы?",
    options: ["<body>", "<meta>", "<head>", "<title>"],
    correctAnswerIndex: 2,
    explanation: "Метаданные размещаются внутри <head>.",
  },
  {
    id: 24,
    category: "HTML",
    type: "multiple-choice",
    question: "Где располагается видимое содержимое страницы?",
    options: ["<head>", "<html>", "<body>", "<main>"],
    correctAnswerIndex: 2,
    explanation: "Все отображаемое содержимое находится в <body>.",
  },
  {
    id: 25,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег задает название страницы во вкладке браузера?",
    options: ["<meta>", "<head>", "<title>", "<caption>"],
    correctAnswerIndex: 2,
    explanation: "Название вкладки определяется тегом <title>.",
  },
  {
    id: 26,
    category: "HTML",
    type: "multiple-choice",
    question:
      "Какой семантический тег обозначает основное содержимое страницы?",
    options: ["<section>", "<article>", "<main>", "<aside>"],
    correctAnswerIndex: 2,
    explanation: "<main> содержит основное уникальное содержимое документа.",
  },
  {
    id: 27,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для навигации по сайту?",
    options: ["<menu>", "<aside>", "<nav>", "<header>"],
    correctAnswerIndex: 2,
    explanation: "<nav> предназначен для блока навигации.",
  },
  {
    id: 28,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег обозначает нижнюю часть страницы?",
    options: ["<bottom>", "<footer>", "<end>", "<aside>"],
    correctAnswerIndex: 1,
    explanation: "<footer> используется для подвала страницы.",
  },
  {
    id: 29,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег обозначает верхнюю часть страницы?",
    options: ["<top>", "<header>", "<head>", "<section>"],
    correctAnswerIndex: 1,
    explanation: "<header> описывает вводную часть страницы или раздела.",
  },
  {
    id: 30,
    category: "HTML",
    type: "multiple-choice",
    question: "Какой тег используется для подключения JavaScript-файла?",
    options: ["<js>", "<script>", "<javascript>", "<code>"],
    correctAnswerIndex: 1,
    explanation: "Внешний JavaScript подключается с помощью тега <script>.",
  },

  {
    id: 31,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство изменяет цвет текста?",
    options: ["font-color", "background-color", "text-color", "color"],
    correctAnswerIndex: 3,
    explanation: "Свойство color отвечает за цвет текста.",
  },
  {
    id: 32,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство изменяет цвет фона элемента?",
    options: ["background-color", "color", "bgcolor", "fill"],
    correctAnswerIndex: 0,
    explanation: "background-color изменяет цвет фона элемента.",
  },
  {
    id: 33,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое значение display делает элемент Flex-контейнером?",
    options: ["block", "inline", "flex", "grid"],
    correctAnswerIndex: 2,
    explanation: "display: flex превращает элемент во Flex-контейнер.",
  },
  {
    id: 34,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое значение display делает элемент Grid-контейнером?",
    options: ["flex", "inline-grid", "grid", "block"],
    correctAnswerIndex: 2,
    explanation: "display: grid создает Grid-контейнер.",
  },
  {
    id: 35,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство задает внешние отступы?",
    options: ["padding", "margin", "gap", "spacing"],
    correctAnswerIndex: 1,
    explanation: "margin отвечает за внешние отступы.",
  },
  {
    id: 36,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство задает внутренние отступы?",
    options: ["margin", "padding", "gap", "space"],
    correctAnswerIndex: 1,
    explanation: "padding определяет внутренние отступы.",
  },
  {
    id: 37,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство делает текст жирным?",
    options: ["font-weight", "font-style", "text-weight", "bold"],
    correctAnswerIndex: 0,
    explanation: "font-weight управляет толщиной шрифта.",
  },
  {
    id: 38,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство изменяет размер шрифта?",
    options: ["text-size", "font-size", "size", "font-scale"],
    correctAnswerIndex: 1,
    explanation: "Размер текста задается через font-size.",
  },
  {
    id: 39,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство делает текст курсивным?",
    options: ["font-style", "text-style", "italic", "font-weight"],
    correctAnswerIndex: 0,
    explanation: "font-style: italic делает текст курсивным.",
  },
  {
    id: 40,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство выравнивает текст по центру?",
    options: ["justify-content", "align-items", "text-align", "center"],
    correctAnswerIndex: 2,
    explanation: "text-align используется для выравнивания текста.",
  },
  {
    id: 41,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство закругляет углы элемента?",
    options: ["border-style", "border-radius", "radius", "round"],
    correctAnswerIndex: 1,
    explanation: "border-radius создает скругленные углы.",
  },
  {
    id: 42,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство добавляет тень элементу?",
    options: ["text-shadow", "shadow", "box-shadow", "element-shadow"],
    correctAnswerIndex: 2,
    explanation: "box-shadow создает тень вокруг элемента.",
  },
  {
    id: 43,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство изменяет прозрачность элемента?",
    options: ["visibility", "opacity", "alpha", "transparent"],
    correctAnswerIndex: 1,
    explanation: "opacity принимает значения от 0 до 1.",
  },
  {
    id: 44,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство используется для задания ширины элемента?",
    options: ["length", "size", "width", "max-width"],
    correctAnswerIndex: 2,
    explanation: "width определяет ширину элемента.",
  },
  {
    id: 45,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство используется для задания высоты элемента?",
    options: ["height", "size", "length", "min-height"],
    correctAnswerIndex: 0,
    explanation: "height задает высоту элемента.",
  },
  {
    id: 46,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство в Flexbox выравнивает элементы по главной оси?",
    options: ["align-items", "justify-content", "align-content", "place-items"],
    correctAnswerIndex: 1,
    explanation: "justify-content выравнивает элементы вдоль главной оси.",
  },
  {
    id: 47,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое свойство в Flexbox выравнивает элементы по поперечной оси?",
    options: ["justify-items", "justify-content", "align-items", "align-self"],
    correctAnswerIndex: 2,
    explanation: "align-items работает по поперечной оси.",
  },
  {
    id: 48,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое свойство задает расстояние между элементами Flex или Grid?",
    options: ["margin", "padding", "spacing", "gap"],
    correctAnswerIndex: 3,
    explanation: "gap создает промежутки между элементами.",
  },
  {
    id: 49,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое значение position оставляет элемент в обычном потоке документа?",
    options: ["absolute", "relative", "static", "fixed"],
    correctAnswerIndex: 2,
    explanation: "static — значение position по умолчанию.",
  },
  {
    id: 50,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое значение position фиксирует элемент относительно окна браузера?",
    options: ["sticky", "relative", "fixed", "absolute"],
    correctAnswerIndex: 2,
    explanation: "fixed закрепляет элемент относительно окна браузера.",
  },
  {
    id: 51,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое значение position позиционирует элемент относительно ближайшего позиционированного родителя?",
    options: ["fixed", "absolute", "sticky", "static"],
    correctAnswerIndex: 1,
    explanation:
      "absolute ищет ближайшего родителя с position, отличным от static.",
  },
  {
    id: 52,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство управляет порядком наложения элементов?",
    options: ["order", "layer", "z-index", "index"],
    correctAnswerIndex: 2,
    explanation: "z-index определяет порядок отображения элементов по оси Z.",
  },
  {
    id: 53,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое свойство скрывает элемент, но сохраняет его место в документе?",
    options: ["display: none", "opacity: 0", "visibility: hidden", "hidden"],
    correctAnswerIndex: 2,
    explanation:
      "visibility: hidden скрывает элемент, но место остается занятым.",
  },
  {
    id: 54,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое значение display полностью убирает элемент из потока документа?",
    options: [
      "visibility: hidden",
      "opacity: 0",
      "display: none",
      "display: hidden",
    ],
    correctAnswerIndex: 2,
    explanation: "display: none удаляет элемент из потока документа.",
  },
  {
    id: 55,
    category: "CSS",
    type: "multiple-choice",
    question: "Какой псевдокласс применяется при наведении курсора?",
    options: [":active", ":focus", ":hover", ":visited"],
    correctAnswerIndex: 2,
    explanation: ":hover применяется при наведении указателя.",
  },
  {
    id: 56,
    category: "CSS",
    type: "multiple-choice",
    question: "Какой псевдокласс применяется к активному элементу формы?",
    options: [":hover", ":focus", ":checked", ":disabled"],
    correctAnswerIndex: 1,
    explanation: ":focus применяется к элементу, получившему фокус.",
  },
  {
    id: 57,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое правило используется для адаптивной верстки?",
    options: ["@font-face", "@keyframes", "@media", "@supports"],
    correctAnswerIndex: 2,
    explanation: "@media позволяет применять стили в зависимости от условий.",
  },
  {
    id: 58,
    category: "CSS",
    type: "multiple-choice",
    question: "Какой селектор имеет наибольшую специфичность?",
    options: [".class", "div", "#id", "*"],
    correctAnswerIndex: 2,
    explanation: "Селектор по id имеет более высокую специфичность.",
  },
  {
    id: 59,
    category: "CSS",
    type: "multiple-choice",
    question:
      "Какое значение box-sizing включает padding и border в общую ширину элемента?",
    options: ["content-box", "border-box", "padding-box", "inherit"],
    correctAnswerIndex: 1,
    explanation: "border-box значительно упрощает верстку.",
  },
  {
    id: 60,
    category: "CSS",
    type: "multiple-choice",
    question: "Какое свойство задает плавную анимацию изменения CSS-свойств?",
    options: ["animation", "transition", "transform", "translate"],
    correctAnswerIndex: 1,
    explanation: "transition позволяет плавно изменять значения CSS-свойств.",
  },

  {
    id: 61,
    category: "JavaScript",
    type: "multiple-choice",
    question:
      "Какое ключевое слово создает переменную, которую нельзя переопределить?",
    options: ["var", "let", "const", "static"],
    correctAnswerIndex: 2,
    explanation: "const создает переменную, которую нельзя переназначить.",
  },
  {
    id: 62,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой оператор используется для строгого сравнения?",
    options: ["==", "=", "===", "!="],
    correctAnswerIndex: 2,
    explanation: "=== сравнивает значение и тип данных.",
  },
  {
    id: 63,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что вернет typeof 'Hello'?",
    options: ["string", "text", "object", "char"],
    correctAnswerIndex: 0,
    explanation: "Строки в JavaScript имеют тип string.",
  },
  {
    id: 64,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой метод добавляет элемент в конец массива?",
    options: ["push", "pop", "shift", "unshift"],
    correctAnswerIndex: 0,
    explanation: "push добавляет элементы в конец массива.",
  },
  {
    id: 65,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой метод удаляет последний элемент массива?",
    options: ["remove", "delete", "pop", "shift"],
    correctAnswerIndex: 2,
    explanation: "pop удаляет последний элемент массива.",
  },
  {
    id: 66,
    category: "JavaScript",
    type: "multiple-choice",
    question:
      "Какой метод создает новый массив после преобразования элементов?",
    options: ["forEach", "map", "filter", "find"],
    correctAnswerIndex: 1,
    explanation: "map возвращает новый массив с измененными элементами.",
  },
  {
    id: 67,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой метод возвращает элементы, которые проходят проверку?",
    options: ["map", "filter", "find", "reduce"],
    correctAnswerIndex: 1,
    explanation: "filter создает новый массив подходящих элементов.",
  },
  {
    id: 68,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой метод возвращает первый найденный элемент?",
    options: ["find", "filter", "search", "includes"],
    correctAnswerIndex: 0,
    explanation: "find возвращает первый элемент, удовлетворяющий условию.",
  },
  {
    id: 69,
    category: "JavaScript",
    type: "multiple-choice",
    question:
      "Какой метод используется для объединения массива в одно значение?",
    options: ["join", "reduce", "concat", "merge"],
    correctAnswerIndex: 1,
    explanation: "reduce сводит массив к одному результату.",
  },
  {
    id: 70,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что делает метод forEach?",
    options: [
      "Создает новый массив",
      "Перебирает элементы массива",
      "Удаляет элементы",
      "Сортирует массив",
    ],
    correctAnswerIndex: 1,
    explanation: "forEach выполняет функцию для каждого элемента массива.",
  },
  {
    id: 71,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Как получить длину массива?",
    options: ["array.size", "array.length", "array.count", "array.length()"],
    correctAnswerIndex: 1,
    explanation: "У массивов есть свойство length.",
  },
  {
    id: 72,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Как проверить, является ли значение массивом?",
    options: [
      "typeof value === 'array'",
      "Array.isArray(value)",
      "value.isArray()",
      "checkArray(value)",
    ],
    correctAnswerIndex: 1,
    explanation: "Array.isArray() проверяет, является ли значение массивом.",
  },
  {
    id: 73,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Как создать объект?",
    options: [
      "const obj = {}",
      "const obj = []",
      "const obj = object()",
      "create obj",
    ],
    correctAnswerIndex: 0,
    explanation: "Литерал {} создает объект.",
  },
  {
    id: 74,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Как получить значение свойства объекта?",
    options: [
      "object->property",
      "object.property",
      "object[property()]",
      "object:get(property)",
    ],
    correctAnswerIndex: 1,
    explanation: "Через точку можно обращаться к свойствам объекта.",
  },
  {
    id: 75,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какой оператор используется для копирования свойств объекта?",
    options: ["spread ...", "copy", "clone", "extends"],
    correctAnswerIndex: 0,
    explanation:
      "Оператор spread (...) позволяет копировать свойства объектов и массивов.",
  },

  {
    id: 76,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что такое замыкание (closure) в JavaScript?",
    options: [
      "Функция, которая удаляет переменные",
      "Функция с областью видимости, где она была создана",
      "Метод массива",
      "Способ создания объекта",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Замыкание позволяет функции запоминать переменные из внешней области видимости.",
  },
  {
    id: 77,
    category: "JavaScript",
    type: "multiple-choice",
    question:
      "Какая область видимости у переменной, объявленной через let внутри блока?",
    options: [
      "Глобальная",
      "Блочная",
      "Только объектная",
      "Нет области видимости",
    ],
    correctAnswerIndex: 1,
    explanation: "let и const имеют блочную область видимости.",
  },
  {
    id: 78,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что произойдет при попытке изменить значение const?",
    options: [
      "Значение изменится",
      "Будет ошибка",
      "Создастся новая переменная",
      "Ничего не произойдет",
    ],
    correctAnswerIndex: 1,
    explanation: "const запрещает переназначение переменной.",
  },
  {
    id: 79,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что делает оператор spread (...)?",
    options: [
      "Удаляет массив",
      "Разворачивает элементы объекта или массива",
      "Создает цикл",
      "Создает функцию",
    ],
    correctAnswerIndex: 1,
    explanation: "Spread позволяет копировать и раскрывать значения.",
  },
  {
    id: 80,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что делает оператор rest (...) в параметрах функции?",
    options: [
      "Собирает несколько аргументов в массив",
      "Удаляет аргументы",
      "Создает объект",
      "Останавливает функцию",
    ],
    correctAnswerIndex: 0,
    explanation: "Rest собирает оставшиеся аргументы в массив.",
  },
  {
    id: 81,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что такое деструктуризация объекта?",
    options: [
      "Удаление объекта",
      "Извлечение свойств объекта в переменные",
      "Копирование объекта",
      "Преобразование объекта в JSON",
    ],
    correctAnswerIndex: 1,
    explanation: "Деструктуризация позволяет удобно получать свойства объекта.",
  },
  {
    id: 82,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что вернет функция без return?",
    options: ["null", "false", "undefined", "0"],
    correctAnswerIndex: 2,
    explanation:
      "Если функция ничего не возвращает, результатом будет undefined.",
  },
  {
    id: 83,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что такое callback-функция?",
    options: [
      "Функция, переданная другой функции как аргумент",
      "Функция без имени",
      "Асинхронная функция",
      "Метод объекта",
    ],
    correctAnswerIndex: 0,
    explanation:
      "Callback вызывается внутри другой функции после выполнения определенного действия.",
  },
  {
    id: 84,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что возвращает Promise?",
    options: [
      "Строку",
      "Объект будущего результата асинхронной операции",
      "Массив",
      "Функцию",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Promise представляет результат асинхронной операции, который появится позже.",
  },
  {
    id: 85,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Какие состояния может иметь Promise?",
    options: [
      "start, stop",
      "open, close",
      "pending, fulfilled, rejected",
      "true, false",
    ],
    correctAnswerIndex: 2,
    explanation: "Promise может быть pending, fulfilled или rejected.",
  },
  {
    id: 86,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Как обработать успешное выполнение Promise?",
    options: [".catch()", ".then()", ".error()", ".success()"],
    correctAnswerIndex: 1,
    explanation: "then() выполняется после успешного завершения Promise.",
  },
  {
    id: 87,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Для чего используется async?",
    options: [
      "Создает массив",
      "Позволяет использовать await внутри функции",
      "Удаляет Promise",
      "Останавливает код",
    ],
    correctAnswerIndex: 1,
    explanation:
      "async делает функцию асинхронной и позволяет использовать await.",
  },
  {
    id: 88,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что делает await?",
    options: [
      "Ждет выполнения Promise",
      "Создает Promise",
      "Удаляет функцию",
      "Перезапускает цикл",
    ],
    correctAnswerIndex: 0,
    explanation:
      "await приостанавливает выполнение async-функции до получения результата Promise.",
  },
  {
    id: 89,
    category: "JavaScript",
    type: "multiple-choice",
    question: "Что такое Event Loop?",
    options: [
      "Цикл for",
      "Механизм обработки асинхронных операций JavaScript",
      "Метод массива",
      "Тип данных",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Event Loop управляет выполнением задач и очередей в JavaScript.",
  },
  {
    id: 90,
    category: "JavaScript",
    type: "multiple-choice",
    question:
      "Какой метод выполняет несколько Promise параллельно и ждет всех результатов?",
    options: [
      "Promise.all()",
      "Promise.wait()",
      "Promise.parallel()",
      "Promise.async()",
    ],
    correctAnswerIndex: 0,
    explanation:
      "Promise.all() запускает несколько Promise и возвращает массив результатов после выполнения всех.",
  },

  {
    id: 91,
    category: "React",
    type: "multiple-choice",
    question: "Что такое React?",
    options: [
      "База данных",
      "JavaScript-библиотека для создания пользовательских интерфейсов",
      "Язык программирования",
      "CSS-фреймворк",
    ],
    correctAnswerIndex: 1,
    explanation: "React — это библиотека JavaScript для создания UI.",
  },
  {
    id: 92,
    category: "React",
    type: "multiple-choice",
    question: "Что такое компонент в React?",
    options: [
      "Файл CSS",
      "Переиспользуемая часть интерфейса",
      "База данных",
      "HTML-тег",
    ],
    correctAnswerIndex: 1,
    explanation: "Компонент — самостоятельная часть UI с собственной логикой.",
  },
  {
    id: 93,
    category: "React",
    type: "multiple-choice",
    question: "Какой синтаксис используется для описания UI в React?",
    options: ["HTML", "JSX", "XML", "Template"],
    correctAnswerIndex: 1,
    explanation:
      "React использует JSX — синтаксис, похожий на HTML внутри JavaScript.",
  },
  {
    id: 94,
    category: "React",
    type: "multiple-choice",
    question: "Что такое props в React?",
    options: [
      "Внутреннее состояние компонента",
      "Данные, передаваемые компоненту",
      "CSS-стили",
      "Методы массива",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Props позволяют передавать данные от родителя к дочернему компоненту.",
  },
  {
    id: 95,
    category: "React",
    type: "multiple-choice",
    question: "Можно ли изменять props внутри компонента?",
    options: [
      "Да, напрямую",
      "Нет, props только для чтения",
      "Только через CSS",
      "Только через useEffect",
    ],
    correctAnswerIndex: 1,
    explanation: "Props являются неизменяемыми данными.",
  },
  {
    id: 96,
    category: "React",
    type: "multiple-choice",
    question: "Какой хук используется для создания состояния?",
    options: ["useEffect", "useState", "useRef", "useMemo"],
    correctAnswerIndex: 1,
    explanation: "useState добавляет состояние в функциональный компонент.",
  },
  {
    id: 97,
    category: "React",
    type: "multiple-choice",
    question: "Что возвращает useState?",
    options: [
      "Объект",
      "Массив со значением и функцией обновления",
      "Promise",
      "Компонент",
    ],
    correctAnswerIndex: 1,
    explanation: "useState возвращает текущее значение и функцию изменения.",
  },
  {
    id: 98,
    category: "React",
    type: "multiple-choice",
    question: "Для чего используется useEffect?",
    options: [
      "Для создания компонентов",
      "Для побочных эффектов",
      "Для стилизации",
      "Для маршрутизации",
    ],
    correctAnswerIndex: 1,
    explanation:
      "useEffect используется для API-запросов, подписок, таймеров и других эффектов.",
  },
  {
    id: 99,
    category: "React",
    type: "multiple-choice",
    question: "Когда выполняется useEffect без массива зависимостей?",
    options: [
      "Один раз",
      "После каждого рендера",
      "Никогда",
      "Только при клике",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Без зависимостей useEffect запускается после каждого рендера.",
  },
  {
    id: 100,
    category: "React",
    type: "multiple-choice",
    question: "Что делает пустой массив зависимостей [] в useEffect?",
    options: [
      "Запускает эффект каждый раз",
      "Запускает эффект один раз после монтирования",
      "Удаляет компонент",
      "Отключает React",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Пустой массив означает выполнение эффекта только после первого рендера.",
  },
  {
    id: 101,
    category: "React",
    type: "multiple-choice",
    question: "Что такое Virtual DOM?",
    options: [
      "Копия браузера",
      "Виртуальное представление DOM в памяти",
      "CSS-анимация",
      "Сервер React",
    ],
    correctAnswerIndex: 1,
    explanation:
      "React использует Virtual DOM для эффективного обновления интерфейса.",
  },
  {
    id: 102,
    category: "React",
    type: "multiple-choice",
    question: "Зачем нужен key при рендеринге списка?",
    options: [
      "Для CSS",
      "Для идентификации элементов React",
      "Для сортировки",
      "Для удаления элементов",
    ],
    correctAnswerIndex: 1,
    explanation: "key помогает React понимать, какие элементы изменились.",
  },
  {
    id: 103,
    category: "React",
    type: "multiple-choice",
    question: "Как правильно передать событие в React?",
    options: [
      "onClick='handle()'",
      "onClick={handle}",
      "click={handle}",
      "event={handle}",
    ],
    correctAnswerIndex: 1,
    explanation: "В React обработчики передаются через camelCase свойства.",
  },
  {
    id: 104,
    category: "React",
    type: "multiple-choice",
    question: "Что такое controlled component?",
    options: [
      "Компонент без состояния",
      "Компонент, где данные формы контролируются React",
      "Компонент CSS",
      "Удаленный компонент",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Controlled component хранит значение формы в состоянии React.",
  },
  {
    id: 105,
    category: "React",
    type: "multiple-choice",
    question: "Как передать данные от ребенка к родителю?",
    options: [
      "Через callback функцию",
      "Через props напрямую",
      "Через HTML",
      "Нельзя",
    ],
    correctAnswerIndex: 0,
    explanation: "Обычно ребенок вызывает функцию, переданную через props.",
  },
  {
    id: 106,
    category: "React",
    type: "multiple-choice",
    question: "Для чего используется useContext?",
    options: [
      "Для глобального состояния",
      "Для создания CSS",
      "Для запросов",
      "Для маршрутов",
    ],
    correctAnswerIndex: 0,
    explanation:
      "Context позволяет передавать данные без прокидывания props через много уровней.",
  },
  {
    id: 107,
    category: "React",
    type: "multiple-choice",
    question: "Что делает useRef?",
    options: [
      "Создает изменяемое значение без ререндера",
      "Создает компонент",
      "Удаляет состояние",
      "Создает маршрут",
    ],
    correctAnswerIndex: 0,
    explanation: "useRef хранит значение между рендерами без обновления UI.",
  },
  {
    id: 108,
    category: "React",
    type: "multiple-choice",
    question: "Для чего используется useMemo?",
    options: [
      "Мемоизация вычислений",
      "Создание состояния",
      "Запросы API",
      "Рендеринг списка",
    ],
    correctAnswerIndex: 0,
    explanation: "useMemo сохраняет результат тяжелого вычисления.",
  },
  {
    id: 109,
    category: "React",
    type: "multiple-choice",
    question: "Для чего используется useCallback?",
    options: [
      "Сохранение функции между рендерами",
      "Создание объекта",
      "Удаление компонента",
      "Работа с CSS",
    ],
    correctAnswerIndex: 0,
    explanation: "useCallback предотвращает лишнее создание функций.",
  },
  {
    id: 110,
    category: "React",
    type: "multiple-choice",
    question: "Что такое React Router?",
    options: [
      "Библиотека для маршрутизации",
      "CSS библиотека",
      "Система базы данных",
      "Хранилище",
    ],
    correctAnswerIndex: 0,
    explanation:
      "React Router позволяет создавать страницы в React-приложении.",
  },
  {
    id: 111,
    category: "React",
    type: "multiple-choice",
    question: "Что делает компонент Fragment?",
    options: [
      "Группирует элементы без лишнего HTML-тега",
      "Удаляет элементы",
      "Создает страницу",
      "Добавляет стили",
    ],
    correctAnswerIndex: 0,
    explanation:
      "Fragment позволяет вернуть несколько элементов без дополнительного div.",
  },
  {
    id: 112,
    category: "React",
    type: "multiple-choice",
    question: "Что происходит при изменении state?",
    options: [
      "Компонент перерисовывается",
      "React закрывается",
      "Удаляется DOM",
      "Меняется CSS",
    ],
    correctAnswerIndex: 0,
    explanation: "Изменение состояния вызывает новый рендер компонента.",
  },
  {
    id: 113,
    category: "React",
    type: "multiple-choice",
    question: "Можно ли использовать несколько useState в одном компоненте?",
    options: ["Нет", "Да", "Только два", "Только один раз"],
    correctAnswerIndex: 1,
    explanation: "В компоненте можно использовать несколько хуков состояния.",
  },
  {
    id: 114,
    category: "React",
    type: "multiple-choice",
    question: "Что такое условный рендеринг?",
    options: [
      "Отображение UI по условию",
      "Удаление React",
      "Создание CSS",
      "Сортировка массива",
    ],
    correctAnswerIndex: 0,
    explanation:
      "React позволяет показывать разные элементы в зависимости от условий.",
  },
  {
    id: 115,
    category: "React",
    type: "multiple-choice",
    question: "Какая библиотека часто используется для управления состоянием?",
    options: ["Redux", "HTML", "CSS", "Webpack"],
    correctAnswerIndex: 0,
    explanation: "Redux — популярное решение для глобального состояния.",
  },
  {
    id: 116,
    category: "React",
    type: "multiple-choice",
    question: "Что такое JSX?",
    options: [
      "HTML внутри JavaScript",
      "Новый язык программирования",
      "База данных",
      "CSS препроцессор",
    ],
    correctAnswerIndex: 0,
    explanation: "JSX позволяет описывать интерфейс прямо в JavaScript.",
  },
  {
    id: 117,
    category: "React",
    type: "multiple-choice",
    question: "Как называется процесс удаления компонента из DOM?",
    options: ["Unmount", "Render", "Mount", "Update"],
    correctAnswerIndex: 0,
    explanation: "Unmount — удаление компонента.",
  },
  {
    id: 118,
    category: "React",
    type: "multiple-choice",
    question: "Что такое props drilling?",
    options: [
      "Передача props через много уровней компонентов",
      "Ошибка React",
      "Удаление props",
      "Стилизация",
    ],
    correctAnswerIndex: 0,
    explanation: "Props drilling — проблема глубокого прокидывания данных.",
  },
  {
    id: 119,
    category: "React",
    type: "multiple-choice",
    question:
      "Какой метод обычно используется для отображения массива компонентов?",
    options: ["map", "filter", "reduce", "for"],
    correctAnswerIndex: 0,
    explanation: "map создает массив React-элементов из массива данных.",
  },
  {
    id: 120,
    category: "React",
    type: "multiple-choice",
    question: "Что является преимуществом компонентов React?",
    options: [
      "Переиспользование UI",
      "Замена JavaScript",
      "Удаление HTML",
      "Работа без браузера",
    ],
    correctAnswerIndex: 0,
    explanation:
      "Компоненты позволяют создавать переиспользуемые части интерфейса.",
  },
];
